# Generated by Django 5.2.7 on 2025-10-19 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_total', models.IntegerField(default=0)),
                ('opening_hours_data', models.JSONField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coffee_shops',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='coffee_shop_latitud_0b836d_idx'), models.Index(fields=['last_updated'], name='coffee_shop_last_up_3ac484_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.IntegerField()),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'search_cache',
                'indexes': [models.Index(fields=['latitude', 'longitude', 'radius'], name='search_cach_latitud_29a334_idx'), models.Index(fields=['expires_at'], name='search_cach_expires_72c899_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_rating', models.IntegerField(blank=True, null=True)),
                ('vibe_rating', models.IntegerField(blank=True, null=True)),
                ('service_rating', models.IntegerField(blank=True, null=True)),
                ('last_visited', models.DateTimeField(blank=True, null=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='shops.coffeeshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_shops',
                'indexes': [models.Index(fields=['user', '-favorited_at'], name='favorite_sh_user_id_ad667c_idx'), models.Index(fields=['user', '-last_visited'], name='favorite_sh_user_id_e2cbf7_idx')],
                'unique_together': {('user', 'shop')},
            },
        ),
    ]
