# Generated by Django 5.2.7 on 2025-10-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='opening_hours_data',
        ),
        migrations.RemoveField(
            model_name='coffeeshop',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='coffeeshop',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='coffeeshop',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='coffeeshop',
            name='user_ratings_total',
        ),
        migrations.RemoveField(
            model_name='coffeeshop',
            name='website',
        ),
    ]
